var DataManager = require("../../core/DataManager.js");
var Utils = require("../../core/Utils");
var TcpManager = require("../../core/TcpManager");


module.exports = function(app) {
  return {
    get: function(request, response) {
      var analysisId = request.params.id;
      // todo: implement it
      if (analysisId) {

      }

      response.json([]);
    },

    post: function(request, response) {
      var analysisObject = request.body.analysis;
      var storager = request.body.storager;

      try {
        analysisObject.type = Utils.getAnalysisType(analysisObject.type_id);

        // if not has project_id, getting from cache
        if (!analysisObject.project_id)
          analysisObject.project_id = app.locals.activeProject.id;

        // temp code
        analysisObject.script_language = "PYTHON";
        analysisObject.schedule_id = 1;
        analysisObject.data_series_id = analysisObject.dataSeries.id;

        var dataSeries = {
          name: analysisObject.name,
          description: "Generated by analysis " + analysisObject.name,
          data_provider_id: analysisObject.data_provider_id,
          data_series_semantic_name: 'ANALYSIS-postgis',
          dataSets: [
            {
              active: true,
              format: {'table_name': 'testTBL'} // todo: adicionar o id do dataseries de entrada
            }
          ]
        };

        DataManager.addAnalysis(analysisObject, dataSeries).then(function(analysisResult) {
          TcpManager.sendData({"Analysis": [analysisResult.toObject()]});
          console.log(analysisResult);
          response.json({status: 200});
        }).catch(function(err) {
          console.log(err);
          Utils.handleRequestError(response, err, 400);
        })
      } catch (err) {
        Utils.handleRequestError(response, err, 400);
      }
    },

    delete: function(request, response) {
      response.json({status: 200});
    }
  };
};
