var Utils = require("./../../Utils");
var DataSeriesBuilder = require("./DataSeriesBuilder");
var Model = require("./../../data-model/Analysis");
var ScheduleModel = require("./../../data-model/Schedule");

/**
 * It simulates a Analysis creation. It is used to build an analysis in order to validate it before save in database
 * 
 * @param {Object} analysisObject - TerraMA² analysis values
 * @param {Object} storager - TerraMA² storager values 
 * @return {Analysis}
 */
function AnalysisBuilder(analysisObject, storager) {
  var rawDataSeries = {
    name: analysisObject.name,
    description: "Generated by analysis " + analysisObject.name,
    data_provider_id: analysisObject.data_provider_id,
    data_series_semantics_id: storager.semantics.format.id,
    dataSets: [
      {
        active: true,
        format: storager.format
      }
    ]
  };

  var dataSeriesModel = DataSeriesBuilder(rawDataSeries);

  analysisObject.dataset_output = dataSeriesModel.dataSets[0].id;
  analysisObject.schedule.id = dataSeriesModel.id;
  analysisObject.schedule = new ScheduleModel(analysisObject.schedule);
  analysisObject.id = dataSeriesModel.id;
  var analysisModel = new Model(analysisObject);
  analysisModel.setDataSeries(rawDataSeries);

  return analysisModel;
}


module.exports = AnalysisBuilder;