/*
  Copyright (C) 2007 National Institute For Space Research (INPE) - Brazil.

  This file is part of TerraMA2 - a free and open source computational
  platform for analysis, monitoring, and alert of geo-environmental extremes.

  TerraMA2 is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  TerraMA2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with TerraMA2. See LICENSE. If not, write to
  TerraMA2 Team at <terrama2-team@dpi.inpe.br>.
*/

/*!
  \file terrama2/gui/config/AddListDialog.hpp

  \brief Services QT Dialog Header

  \author Evandro Delatin
  \author Raphael Willian da Costa
  \author Raphael Meloni
*/

#ifndef _ADD_LIST_DLG_H_
#define _ADD_LIST_DLG_H_

// TerraMA2
#include "AdditionalMapList.hpp"

// Generated by QT
#include "ui_AddListDialog.h"

//! Class reponsible for show the selection dialog
class AddListDialog : public QDialog, private Ui::AddListDialog
{
Q_OBJECT

public:
  AddListDialog(QWidget* parent = 0, Qt::WFlags f = 0 );
  ~AddListDialog();

  bool setFields(std::vector<wsNotificationFilter> notifications, AdditionalMapList* addList);
  void getFields(std::vector<wsNotificationFilter>& notifications, bool& changed);
  void fillListNotification();

private:
  std::vector<wsNotificationFilter> notificationList;
};


#endif