/*
  Copyright (C) 2007 National Institute For Space Research (INPE) - Brazil.

  This file is part of TerraMA2 - a free and open source computational
  platform for analysis, monitoring, and alert of geo-environmental extremes.

  TerraMA2 is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  TerraMA2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with TerraMA2. See LICENSE. If not, write to
  TerraMA2 Team at <terrama2-team@dpi.inpe.br>.
*/

/*!
  \file terrama2/gui/config/AnalysisConditionDialog.hpp

  \brief Definition of class AnalysisConditionDialog.hpp

  \author Evandro Delatin
  \author Raphael Willian da Costa
*/

#ifndef _ANALYSIS_CONDITIONDLG_H_
#define _ANALYSIS_CONDITIONDLG_H_

// Generated by QT
#include "ui_AnalysisConditionDialog.h"

class AnalysisList;
class RiskMapList;
class QAction;

class AnalysisConditionDialog : public QDialog, private Ui::AnalysisConditionDialog
{
Q_OBJECT

public:
  AnalysisConditionDialog(const AnalysisList* anaList, const RiskMapList* riskList,
                       int currAnaIndex, QString currAnaName, 
                       int condAnaId, QString condAnaScript,
                       QWidget* parent = 0, Qt::WFlags f = 0 );
  ~AnalysisConditionDialog();

  int     conditionAnalysisId() { return _anaId; }
  QString conditionRule()       { return _rule;  }

private slots:
  void okPressed();
  void analysisChanged(int row);
  void addTextToScript(QAction* act);
  void syntaxCheckRequested();
  
private:
  void fillZoneOperatorMenu();
  void fillResultsMenu();
  void fillFunctionsMenu();
  void fillCommandsMenu();
  void fillAttributesMenu(int riskMapId);

  int                 _anaId;
  QString             _rule;
  const AnalysisList* _anaList;
  const RiskMapList*  _riskList;
};


#endif

