/*
  Copyright (C) 2007 National Institute For Space Research (INPE) - Brazil.

  This file is part of TerraMA2 - a free and open source computational
  platform for analysis, monitoring, and alert of geo-environmental extremes.

  TerraMA2 is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  TerraMA2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with TerraMA2. See LICENSE. If not, write to
  TerraMA2 Team at <terrama2-team@dpi.inpe.br>.
*/

/*!
  \file terrama2/gui/config/ArchivingItemsListDialog.hpp

  \brief Definition of ArchivingItemsListDialog.hpp class

  \author Evandro Delatin
  \author Raphael Willian da Costa
*/

#ifndef _ARCHIVINGITEMSLISTDLG_H_
#define _ARCHIVINGITEMSLISTDLG_H_

// TerraMA2
#include "analysisList.h"
#include "remoteWeatherServerList.h"

// Generated by QT
#include "ui_ArchivingItemsListDialog.h"

// QT
#include <QString>
#include <QList>
#include <QPair>

class ArchivingItemsListDialog : public QDialog, private Ui::ArchivingItemsListDialog
{
Q_OBJECT

public:
  ArchivingItemsListDialog(RemoteWeatherServerList* rwsl, AnalysisList* anaList, QList< QPair<QString, int> > conditionList, QWidget* parent = 0, Qt::WFlags f = 0 );
  ~ArchivingItemsListDialog();
  wsArchivingRule getFields();
  void setFields(QString type, int id, wsArchivingRuleAction action, int condValue, QString condStr, bool createFilter);
  static QString getActionString(wsArchivingRuleAction action);
  static QString getTypeString(wsArchivingRuleType type);
  static wsArchivingRuleType getTypeWS(QString typeStr);

private slots:
  void setTypeChanged(int);
  void setObjectChanged(int);
  void setActionChanged(int);
  void enableConditionDate(bool enable);
  
private:
  RemoteWeatherServerList* _rwsl;
  AnalysisList* _anaList;
  void fillItemNameCmb(int type);
};


#endif
