/************************************************************************************
TerraMA² is a development platform of Monitoring, Analysis and Alert for
geoenvironmental extremes. Applied to natural disasters, quality of water / air / atmosphere,
tailings basins, epidemics and others.Copyright © 2012 INPE.

This code is part of the TerraMA² framework.
This framework is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

You should have received a copy of the GNU General Public
License along with this library.

The authors reassure the license terms regarding the warranties.
They specifically disclaim any warranties, including, but not limited to,
the implied warranties of merchantability and fitness for a particular purpose.
The library provided hereunder is on an "as is" basis, and the authors have no
obligation to provide maintenance, support, updates, enhancements,
or modifications.

In no event shall INPE or K2 SISTEMAS be held liable to any party for direct, indirect,
special, incidental, or consequential damages arising out of the use of this
library and its documentation.
*************************************************************************************/

/*!
 * \file MainDialog.hpp
 *
 * \brief Definicao da classe MainDialog
 *
 * \author Carlos Augusto Teixeira Mendes
 * \date february, 2008 
 * \version $Id$
 *
 */
 
#ifndef _MAINDLG_H_
#define _MAINDLG_H_

#include <QList>

// Generated by QT
#include "ui_MainDialogForm.h"

class MainDialogTab;
class Services;

/*! \brief Classe que implementa as açoes do diálogo principal
*/      
class MainDialog : public QMainWindow, private Ui::MainDialogForm
{
Q_OBJECT

public:
  MainDialog(QWidget* parent = 0, Qt::WindowFlags f = 0 );
  ~MainDialog();

  //! Retorna o próprio objeto convertido para um Ui::MainDialog
  Ui::MainDialogForm* ui() { return this; }

// protected:
// 	void closeEvent(QCloseEvent* close);

// private slots:
//   void tabChangeRequested(int index);
//   void configOpenRequested();
//   void saveRequested();
//   void refreshRequested();
//   void enableRefreshAction();
//   void disableRefreshAction();
//   void configPropertiesRequested();
//   void executeStudyRequested();
//   void showConsoleRequested();
//   void archiveRequested();
//   void executeTerraMEPlayerRequested();
  
// private:
//   void loadLastConfig();
//   void saveLastConfig();
//   void setConfigFileName(QString configFileName);
//   QString abrevFileName(QString fileName, int size);
//   void loadData(bool initOnly = false);
//   void enableConfigActions(bool mode);

  QList<MainDialogTab*> _tabList;         //!< Lista de gerenciadores das fichas da janela 
//   int                _currentTabIndex; //!< Indice do tab corrente
//   Services*          _manager;         //!< Gerenciador de serviços e dados lidos dos mesmos
//   QString            _configFileName;  //!< Nome do arquivo de configuração
//   bool               _changeConfig;    //!< Flag indicativa de alteração no arquivo de configuração
};


#endif

