module.exports = function(app) {
  var express = require('express');
  var path = require('path');

  app.use(app.locals.BASE_URL + 'externals/jquery/dist/jquery.min.js', express.static(path.join(__dirname, 'node_modules/jquery/dist/jquery.min.js')));
  app.use(app.locals.BASE_URL + 'externals/moment/moment.js', express.static(path.join(__dirname, 'node_modules/moment/moment.js')));
  app.use(app.locals.BASE_URL + 'externals/moment/locale/pt-br.js', express.static(path.join(__dirname, 'node_modules/moment/locale/pt-br.js')));
  app.use(app.locals.BASE_URL + 'externals/moment/locale/es.js', express.static(path.join(__dirname, 'node_modules/moment/locale/es.js')));
  app.use(app.locals.BASE_URL + 'externals/moment/locale/fr.js', express.static(path.join(__dirname, 'node_modules/moment/locale/fr.js')));
  app.use(app.locals.BASE_URL + 'externals/intl-tel-input/build/css/intlTelInput.css', express.static(path.join(__dirname, 'node_modules/intl-tel-input/build/css/intlTelInput.css')));
  app.use(app.locals.BASE_URL + 'externals/intl-tel-input/build/js/intlTelInput.js', express.static(path.join(__dirname, 'node_modules/intl-tel-input/build/js/intlTelInput.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-material/angular-material.min.css', express.static(path.join(__dirname, 'node_modules/angular-material/angular-material.min.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-material/angular-material.min.js', express.static(path.join(__dirname, 'node_modules/angular-material/angular-material.min.js')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/bootstrap/css/bootstrap.min.css', express.static(path.join(__dirname, 'node_modules/admin-lte/bootstrap/css/bootstrap.min.css')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/dist/js/app.min.js', express.static(path.join(__dirname, 'node_modules/admin-lte/dist/js/app.min.js')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/dist/css/AdminLTE.min.css', express.static(path.join(__dirname, 'node_modules/admin-lte/dist/css/AdminLTE.min.css')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/dist/css/skins/skin-blue.min.css', express.static(path.join(__dirname, 'node_modules/admin-lte/dist/css/skins/skin-blue.min.css')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js', express.static(path.join(__dirname, 'node_modules/admin-lte/plugins/jQuery/jQuery-2.1.4.min.js')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/plugins/fastclick/fastclick.min.js', express.static(path.join(__dirname, 'node_modules/admin-lte/plugins/fastclick/fastclick.min.js')));
  app.use(app.locals.BASE_URL + 'externals/AdminLTE/bootstrap/js/bootstrap.min.js', express.static(path.join(__dirname, 'node_modules/admin-lte/bootstrap/js/bootstrap.min.js')));
  app.use(app.locals.BASE_URL + 'externals/font-awesome/css/font-awesome.min.css', express.static(path.join(__dirname, 'node_modules/font-awesome/css/font-awesome.min.css')));
  app.use(app.locals.BASE_URL + 'externals/datatables/media/css/jquery.dataTables.css', express.static(path.join(__dirname, 'node_modules/datatables/media/css/jquery.dataTables.css')));
  app.use(app.locals.BASE_URL + 'externals/datatables/media/js/jquery.dataTables.min.js', express.static(path.join(__dirname, 'node_modules/datatables/media/js/jquery.dataTables.min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular/angular.min.js', express.static(path.join(__dirname, 'node_modules/angular/angular.min.js')));
  app.use(app.locals.BASE_URL + 'externals/i18n-node-angular/i18n-node-angular.js', express.static(path.join(__dirname, 'node_modules/i18n-node-angular/i18n-node-angular.js')));
  app.use(app.locals.BASE_URL + 'externals/ng-file-upload/ng-file-upload.min.js', express.static(path.join(__dirname, 'node_modules/ng-file-upload/dist/ng-file-upload.min.js')));
  app.use(app.locals.BASE_URL + 'externals/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css', express.static(path.join(__dirname, 'node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-ui-select/dist/select.min.css', express.static(path.join(__dirname, 'node_modules/ui-select/dist/select.min.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-ui-select/dist/select.min.js', express.static(path.join(__dirname, 'node_modules/ui-select/dist/select.min.js')));
  app.use(app.locals.BASE_URL + 'externals/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js', express.static(path.join(__dirname, 'node_modules/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-eonasdan-datetimepicker/dist/angular-eonasdan-datetimepicker.min.js', express.static(path.join(__dirname, 'node_modules/angular-eonasdan-datetimepicker/dist/angular-eonasdan-datetimepicker.min.js')));
  app.use(app.locals.BASE_URL + 'externals/tinycolor/dist/tinycolor-min.js', express.static(path.join(__dirname, 'node_modules/tinycolor2/dist/tinycolor-min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-color-picker/dist/angularjs-color-picker.min.js', express.static(path.join(__dirname, 'node_modules/angularjs-color-picker/dist/angularjs-color-picker.min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-color-picker/dist/angularjs-color-picker.min.css', express.static(path.join(__dirname, 'node_modules/angularjs-color-picker/dist/angularjs-color-picker.min.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-color-picker/dist/themes/angularjs-color-picker-bootstrap.min.css', express.static(path.join(__dirname, 'node_modules/angularjs-color-picker/dist/themes/angularjs-color-picker-bootstrap.min.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-tree-control/css/tree-control.css', express.static(path.join(__dirname, 'node_modules/angular-tree-control/css/tree-control.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-tree-control/css/tree-control-attribute.css', express.static(path.join(__dirname, 'node_modules/angular-tree-control/css/tree-control-attribute.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-tree-control/angular-tree-control.js', express.static(path.join(__dirname, 'node_modules/angular-tree-control/angular-tree-control.js')));
  app.use(app.locals.BASE_URL + 'externals/ace-builds/src/ace.js', express.static(path.join(__dirname, 'node_modules/ace-builds/src/ace.js')));
  app.use(app.locals.BASE_URL + 'externals/ace-builds/src/ext-language_tools.js', express.static(path.join(__dirname, 'node_modules/ace-builds/src/ext-language_tools.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-sanitize/angular-sanitize.js', express.static(path.join(__dirname, 'node_modules/angular-sanitize/angular-sanitize.js')));
  app.use(app.locals.BASE_URL + 'externals/tv4/tv4.js', express.static(path.join(__dirname, 'node_modules/tv4/tv4.js')));
  app.use(app.locals.BASE_URL + 'externals/objectpath/lib/ObjectPath.js', express.static(path.join(__dirname, 'node_modules/objectpath/lib/ObjectPath.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-schema-form/dist/schema-form.js', express.static(path.join(__dirname, 'node_modules/angular-schema-form/dist/schema-form.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-schema-form/dist/bootstrap-decorator.min.js', express.static(path.join(__dirname, 'node_modules/angular-schema-form/dist/bootstrap-decorator.min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-aria/angular-aria.min.js', express.static(path.join(__dirname, 'node_modules/angular-aria/angular-aria.min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-animate/angular-animate.min.js', express.static(path.join(__dirname, 'node_modules/angular-animate/angular-animate.min.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-wizard/dist/angular-wizard.min.css', express.static(path.join(__dirname, 'node_modules/angular-wizard/dist/angular-wizard.min.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-wizard/dist/angular-wizard.js', express.static(path.join(__dirname, 'node_modules/angular-wizard/dist/angular-wizard.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-xeditable/dist/css/xeditable.css', express.static(path.join(__dirname, 'node_modules/angular-xeditable/dist/css/xeditable.css')));
  app.use(app.locals.BASE_URL + 'externals/angular-xeditable/dist/js/xeditable.js', express.static(path.join(__dirname, 'node_modules/angular-xeditable/dist/js/xeditable.js')));
  app.use(app.locals.BASE_URL + 'externals/angular-ui-router/release/angular-ui-router.min.js', express.static(path.join(__dirname, 'node_modules/angular-ui-router/release/angular-ui-router.min.js')));
};