#!/bin/sh

#
# Install web dependencies
#

npm install bower -g
npm install grunt -g

(
  cd /usr/local/webapp
  npm install
  bower install --allow-root
  grunt
)

(
  cd /usr/local/webcomponents
  npm install
  bower install --allow-root
  grunt
)

(
  cd /usr/local/webmonitor
  npm install
  bower install --allow-root
)

#
# Install and configure pm2
#

# Check if pm2 is already installed
npm list pm2 -g
if [ $? != 0 ]; then
  # Install pm2
  npm install pm2 -g
  # Allows the service to start with the system
  env PATH=$PATH:/usr/local/bin pm2 startup
fi

# Add webapp to pm2 startup
(
  cd /usr/local/webapp
  pm2 start bin/www --name webapp
  pm2 save
)

# Add webmonitor to pm2 startup
(
  cd /usr/local/webmonitor
  pm2 start bin/www --name webmonitor
  pm2 save
)
