/*
  Copyright (C) 2007 National Institute For Space Research (INPE) - Brazil.

  This file is part of TerraMA2 - a free and open source computational
  platform for analysis, monitoring, and alert of geo-environmental extremes.

  TerraMA2 is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  TerraMA2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with TerraMA2. See LICENSE. If not, write to
  TerraMA2 Team at <terrama2-team@dpi.inpe.br>.
*/

/*!
  \file terrama2/gui/config/AnalysisFillCellOpDialog.hpp

  \brief Definition of class AnalysisFillCellOpDialog

  \author Evandro Delatin
  \author Raphael Willian da Costa
*/

#ifndef _ANALYSIS_FILL_CELL_OP_DLG_H_
#define _ANALYSIS_FILL_CELL_OP_DLG_H_

// Generated by QT
#include "ui_AnalysisFillCellOpDialog.h"

class Services;
class Analysis;
class QListWidget;

class AnalysisFillCellOpDialog : public QDialog, private Ui::AnalysisFillCellOpDialog
{
  Q_OBJECT

public:
  AnalysisFillCellOpDialog(Services* manager, QListWidget* analysisTerraMEListWidget, QWidget* parent = 0, Qt::WFlags f = (Qt::WindowSystemMenuHint | Qt::WindowTitleHint));
  ~AnalysisFillCellOpDialog();

  void setFields(Services* manager, std::vector<struct wsFillOperation> fillOperations);
  void getFields(std::vector<struct wsFillOperation>& fillOperations, bool& changed);

private slots:
  void setChanged();
  void addFillOp();
  void delFillOp();
  void validateOperations();

private:
  bool _ignoreChangeEvents;
  bool _changed;
  QMap<int, QString> _fillOpsMap;
  QMap<QString, int> _weatherGridNameToIndexMap;
  QMap<QString, int> _weatherGridNameToIDMap;
};


#endif