/*
  Copyright (C) 2007 National Institute For Space Research (INPE) - Brazil.

  This file is part of TerraMA2 - a free and open source computational
  platform for analysis, monitoring, and alert of geo-environmental extremes.

  TerraMA2 is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  TerraMA2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with TerraMA2. See LICENSE. If not, write to
  TerraMA2 Team at <terrama2-team@dpi.inpe.br>.
*/

/*!
  \file terrama2/gui/config/AnalysisListDialog.hpp

  \brief Definition of AnalysisListDialog.hpp class

  \author Evandro Delatin
  \author Raphael Willian da Costa
  \author Celso Luiz Ramos Cruz
*/


#ifndef _ANALYSISLISTDLG_H_
#define _ANALYSISLISTDLG_H_

// TerraMA2
#include "analysisList.h"
#include "soapModAnaliseProxy.h"

// Generated by QT
#include "ui_AnalysisListDialog.h"

// QT
#include <QList>


class AnalysisListDialog : public QDialog, private Ui::AnalysisListDialog
{
Q_OBJECT

public:
  AnalysisListDialog(bool hideWarningCombo, QWidget* parent = 0, Qt::WFlags f = 0 );
  ~AnalysisListDialog();

  bool setFields(const std::vector<struct wsAnalysisRule>& analysisRules, AnalysisList* anaList);
  bool setFields(const std::vector<struct wsUserView>& userViews, AnalysisList* anaList);
  void getFields(QList<int>& newIDSelectedAnalyses, bool& changed);
  void getLevels(int& email, int& cellphone, int& report);

private:
  bool findAnalysisRule(const std::vector<struct wsUserView>& userViews, const wsAnalysisRule& anaRule);
  bool findAnalysisRule(const std::vector<struct wsAnalysisRule>& analysisRules, const wsAnalysisRule& anaRule);
  void fillWarningComboBox(QComboBox* combo, int currentIndex = 0);
  void fillReportComboBox(QComboBox* combo, int currentIndex = 0);
};


#endif

